[package]
name = "shevon"
version = "1.0.0"
description = "Scientific calculator emulator"
authors = ["Shevon"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "shevon_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
log = "0.4"
tauri = { version = "2", features = [] }
tauri-plugin-log = "2"
tauri-plugin-global-shortcut = "2"
